import type { Metadata } from "next";
import { Geist, Geist_Mono, Urbanist, Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";
import { ToastProvider } from "@/components/notifications/ToastProvider";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";


const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ['latin'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <ClerkProvider>
      <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${urbanist.variable} antialiased`}
      >
        <ReactQueryProvider>
        <ToastProvider>
          <main className="relative bg-[#111] selection:bg-[#3f3f3f] selection:text-[#ededed]">
            <header className="absolute z-50 w-full flex justify-center items-center">
              <Navigation />
            </header>
            <div className="">
              {children}
            </div>
          </main>
        </ToastProvider>
        </ReactQueryProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
